"""
elevata – Metadata-driven Data Platform Framework
Copyright © 2025-2026 Ilona Tag
SPDX-License-Identifier: AGPL-3.0-only

postgres reserved keywords for elevata.

Source: https://www.postgresql.org/docs/current/sql-keywords-appendix.html

Notes:
  - Stored as UPPERCASE tokens.
  - Generated by elevata_generate_reserved_keywords; do not edit by hand.
"""

from __future__ import annotations

RESERVED_KEYWORDS: frozenset[str] = frozenset({
  "ALL",
  "ALTER",
  "ANALYSE",
  "ANALYZE",
  "AND",
  "ANY",
  "AS",
  "ASC",
  "ASYMMETRIC",
  "BOTH",
  "BY",
  "CASE",
  "CAST",
  "CHECK",
  "COLLATE",
  "COLUMN",
  "CONSTRAINT",
  "CREATE",
  "CURRENT_CATALOG",
  "CURRENT_DATE",
  "CURRENT_ROLE",
  "CURRENT_TIME",
  "CURRENT_TIMESTAMP",
  "CURRENT_USER",
  "DEFAULT",
  "DEFERRABLE",
  "DELETE",
  "DESC",
  "DISTINCT",
  "DO",
  "DROP",
  "ELSE",
  "END",
  "FALSE",
  "FOREIGN",
  "FROM",
  "GROUP",
  "HAVING",
  "IN",
  "INITIALLY",
  "INSERT",
  "JOIN",
  "LATERAL",
  "LEADING",
  "LIMIT",
  "LOCALTIME",
  "LOCALTIMESTAMP",
  "MERGE",
  "NOT",
  "NULL",
  "ON",
  "ONLY",
  "OR",
  "ORDER",
  "PLACING",
  "PRIMARY",
  "REFERENCES",
  "SELECT",
  "SESSION_USER",
  "SOME",
  "SYMMETRIC",
  "SYSTEM_USER",
  "TABLE",
  "THEN",
  "TRAILING",
  "TRUE",
  "UNIQUE",
  "UPDATE",
  "USER",
  "USING",
  "VARIADIC",
  "WHEN",
  "WHERE",
})
