# Generated by Django 5.2.7 on 2026-01-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_create_default_target_schemas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryunionoutputcolumn',
            old_name='name',
            new_name='output_name',
        ),
        migrations.AddField(
            model_name='queryunionoutputcolumn',
            name='decimal_precision',
            field=models.IntegerField(blank=True, help_text='Optional precision for DECIMAL/NUMERIC (e.g., DECIMAL(18,2)).', null=True),
        ),
        migrations.AddField(
            model_name='queryunionoutputcolumn',
            name='decimal_scale',
            field=models.IntegerField(blank=True, help_text='Optional scale for DECIMAL/NUMERIC (e.g., DECIMAL(18,2)).', null=True),
        ),
        migrations.AddField(
            model_name='queryunionoutputcolumn',
            name='max_length',
            field=models.IntegerField(blank=True, help_text='Optional length parameter (e.g., VARCHAR(100)).', null=True),
        ),
    ]
