# Generated by Django 5.2.7 on 2026-02-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_queryunionoutputcolumn_modifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='type',
            field=models.CharField(choices=[('redshift', 'Amazon Redshift'), ('s3', 'Amazon S3 Storage (manual, no reflection)'), ('azureblob', 'Azure Blob Storage (manual, no reflection)'), ('csv', 'CSV File(s) (manual, no reflection)'), ('clickhouse', 'ClickHouse (beta, limited reflection)'), ('databricks', 'Databricks SQL'), ('duckdb', 'DuckDB'), ('exasol', 'Exasol (manual, no reflection)'), ('excel', 'Excel / XLSX File(s) (manual, no reflection)'), ('bigquery', 'Google BigQuery'), ('gcs', 'Google Cloud Storage (manual, no reflection)'), ('graphql', 'GraphQL API (manual, no reflection)'), ('db2', 'IBM DB2 (manual, no reflection)'), ('json', 'JSON File(s) (manual, no reflection)'), ('jsonl', 'JSON Lines File(s) (manual, no reflection)'), ('fabric_warehouse', 'Microsoft Fabric Warehouse'), ('mysql', 'MySQL / MariaDB'), ('oracle', 'Oracle'), ('parquet', 'Parquet File(s) (manual, no reflection)'), ('postgres', 'PostgreSQL'), ('presto', 'Presto (beta, limited reflection)'), ('rest', 'REST API (manual, no reflection)'), ('hana', 'SAP HANA (manual, no reflection)'), ('sapr3', 'SAP R/3 (manual, no reflection)'), ('sftp', 'SFTP Location (manual, no reflection)'), ('mssql', 'SQL Server'), ('sqlite', 'SQLite'), ('snowflake', 'Snowflake'), ('teradata', 'Teradata (manual, no reflection)'), ('trino', 'Trino (beta, limited reflection)')], help_text='System type / backend technology. Used for import and adapter logic.', max_length=20),
        ),
        migrations.AlterField(
            model_name='targetcolumn',
            name='lineage_origin',
            field=models.CharField(choices=[('direct', 'Direct'), ('derived', 'Derived'), ('lookup_join', 'Lookup Join'), ('constant', 'Constant'), ('surrogate_key', 'Surrogate Key'), ('foreign_key', 'Foreign Key'), ('query_derived', 'Query Derived')], default='direct', help_text='How this column is derived: direct source field, derived calculation, lookup join, constant, etc.', max_length=20),
        ),
    ]
