# Generated by Django 5.2.7 on 2026-02-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_alter_targetcolumn_lineage_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetdataset',
            name='incremental_strategy',
            field=models.CharField(choices=[('full', 'Full load (truncate + reload)'), ('append', 'Append-only incremental load'), ('merge', 'Merge (upsert by business key, handle deletes)'), ('snapshot', 'Snapshot-based load'), ('historize', 'Historization (SCD2) dataset')], default='full', help_text='How this dataset is loaded.\n- full: always full refresh (truncate + reload)\n- append: append-only incremental load\n- merge: upsert by business key and handle deletes\n- snapshot: periodic snapshots by watermark/date\n- historize: SCD2 history dataset (system-managed history load)', max_length=20),
        ),
        migrations.AlterField(
            model_name='targetschema',
            name='incremental_strategy_default',
            field=models.CharField(choices=[('full', 'Full load (truncate + reload)'), ('append', 'Append-only incremental load'), ('merge', 'Merge (upsert by business key, handle deletes)'), ('snapshot', 'Snapshot-based load'), ('historize', 'Historization (SCD2) dataset')], default='full', help_text='Default incremental loading strategy for datasets in this schema when the source is incremental. For non-incremental sources, a full refresh is always used.', max_length=20),
        ),
    ]
