# Generated by Django 5.2.7 on 2026-02-21 18:35

from django.db import migrations, models


def set_payload_role(apps, schema_editor):
  TargetColumn = apps.get_model("metadata", "TargetColumn")
  (
    TargetColumn.objects
    .filter(target_column_name="payload")
    .filter(system_role__in=["", None])
    .update(system_role="payload")
  )


def unset_payload_role(apps, schema_editor):
  TargetColumn = apps.get_model("metadata", "TargetColumn")
  (
    TargetColumn.objects
    .filter(target_column_name="payload")
    .filter(system_role="payload")
    .update(system_role="")
  )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_update_hist_incremental_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedataset',
            name='ingestion_config',
            field=models.JSONField(blank=True, help_text='Optional config for ingestion from non-relational sources (REST, files, etc.). This is a contracted JSON structure interpreted by ingestion connectors. Examples: endpoint path, query template/params, pagination strategy, record JSON path, archive policy.', null=True),
        ),
        migrations.AddField(
            model_name='sourcecolumn',
            name='json_path',
            field=models.CharField(blank=True, help_text='Optional JSON path for semi-structured sources (REST/files), e.g. $.customer.id', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='type',
            field=models.CharField(choices=[('redshift', 'Amazon Redshift'), ('s3', 'Amazon S3 Storage (manual, no reflection)'), ('azureblob', 'Azure Blob Storage (manual, no reflection)'), ('csv', 'CSV File(s)'), ('clickhouse', 'ClickHouse (beta, limited reflection)'), ('databricks', 'Databricks SQL'), ('duckdb', 'DuckDB'), ('exasol', 'Exasol (manual, no reflection)'), ('excel', 'Excel / XLSX File(s)'), ('bigquery', 'Google BigQuery'), ('gcs', 'Google Cloud Storage (manual, no reflection)'), ('graphql', 'GraphQL API (manual, no reflection)'), ('db2', 'IBM DB2 (manual, no reflection)'), ('json', 'JSON File(s)'), ('jsonl', 'JSON Lines File(s)'), ('fabric_warehouse', 'Microsoft Fabric Warehouse'), ('mysql', 'MySQL / MariaDB'), ('oracle', 'Oracle'), ('parquet', 'Parquet File(s)'), ('postgres', 'PostgreSQL'), ('presto', 'Presto (beta, limited reflection)'), ('rest', 'REST API'), ('hana', 'SAP HANA (manual, no reflection)'), ('sapr3', 'SAP R/3 (manual, no reflection)'), ('sftp', 'SFTP Location (manual, no reflection)'), ('mssql', 'SQL Server'), ('sqlite', 'SQLite'), ('snowflake', 'Snowflake'), ('teradata', 'Teradata (manual, no reflection)'), ('trino', 'Trino (beta, limited reflection)')], help_text='System type / backend technology. Used for import and adapter logic.', max_length=20),
        ),
        migrations.AlterField(
            model_name='targetcolumn',
            name='system_role',
            field=models.CharField(blank=True, choices=[('', '—'), ('business_key', 'Business key'), ('surrogate_key', 'Surrogate key'), ('foreign_key', 'Foreign key'), ('entity_key', 'Entity key'), ('row_hash', 'Row hash'), ('payload', 'Payload'), ('load_run_id', 'Load run id'), ('loaded_at', 'Loaded at timestamp'), ('version_started_at', 'Version started at'), ('version_ended_at', 'Version ended at'), ('version_state', 'Version state')], default='', help_text='Semantic role for system-managed columns. Used to reliably render/execute technical columns (e.g. payload, load_run_id, loaded_at) and to support forensics without relying on naming conventions.', max_length=30),
        ),
        migrations.RunPython(set_payload_role, reverse_code=unset_payload_role),
    ]
