# Generated by Django 5.2.7 on 2026-03-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_extend_model_for_ingestion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sourcedatasetownership',
            table='source_dataset_ownership',
        ),
        migrations.AlterModelTable(
            name='targetdatasetjoin',
            table='target_dataset_join',
        ),
        migrations.AlterModelTable(
            name='targetdatasetjoinpredicate',
            table='target_dataset_join_predicate',
        ),
        migrations.AlterModelTable(
            name='targetdatasetownership',
            table='target_dataset_ownership',
        ),
        migrations.AlterModelTable(
            name='targetdatasetreferencecomponent',
            table='target_dataset_reference_component',
        ),
    ]
