# Generated by Django 6.0.4 on 2026-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_alter_sourcedatasetownership_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetdatasetreference',
            name='inferred_members_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, controlled load execution may create inferred parent members for non-null child reference values that do not yet exist in the referenced dataset. Disabled by default because this mutates parent data during child loads.'),
        ),
        migrations.AlterField(
            model_name='targetcolumn',
            name='system_role',
            field=models.CharField(blank=True, choices=[('', '—'), ('business_key', 'Business key'), ('surrogate_key', 'Surrogate key'), ('foreign_key', 'Foreign key'), ('entity_key', 'Entity key'), ('row_hash', 'Row hash'), ('payload', 'Payload'), ('load_run_id', 'Load run id'), ('loaded_at', 'Loaded at timestamp'), ('inferred_member', 'Inferred member'), ('default_member', 'Default member'), ('version_started_at', 'Version started at'), ('version_ended_at', 'Version ended at'), ('version_state', 'Version state')], default='', help_text='Semantic role for system-managed columns. Used to reliably render/execute technical columns (e.g. payload, load_run_id, loaded_at) and to support forensics without relying on naming conventions.', max_length=30),
        ),
    ]
