# Generated by Django 6.0.4 on 2026-07-05 14:55

from django.db import migrations, models


def enable_fallback_for_existing_inferred_references(apps, schema_editor):
  TargetDatasetReference = apps.get_model("metadata", "TargetDatasetReference")
  (
    TargetDatasetReference.objects
    .filter(inferred_members_enabled=True)
    .update(default_member_fallback_enabled=True)
  )


class Migration(migrations.Migration):

  dependencies = [
    ('metadata', '0009_controlled_reference_members_contract'),
  ]

  operations = [
    migrations.AddField(
      model_name='targetdatasetreference',
      name='default_member_fallback_enabled',
      field=models.BooleanField(default=False, help_text="If enabled, controlled load execution may map unresolved child reference keys to the referenced dataset's default member. This keeps modeled references joinable for null, empty, incomplete, or otherwise unresolved child reference values. When inferred members are enabled, this fallback is automatically enabled as a modeling default, but it can be disabled explicitly afterwards."),
    ),
      migrations.RunPython(
      enable_fallback_for_existing_inferred_references,
      migrations.RunPython.noop,
    ),
]
