# Generated by Django 6.0.7 on 2026-08-22 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_portable_generated_hash_expressions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialload',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description of the purpose of this Partial Load execution scope.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partialload',
            name='name',
            field=models.CharField(help_text="Short code for this named execution scope. Used as the Partial Load name in execution manifests and scheduler integrations. The name 'full' is reserved for the implicit full execution scope.", max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Must start with a lowercase letter and contain only lowercase letters and digits. Max length is 10 characters.', regex='^[a-z][a-z0-9]{0,9}$')]),
        ),
        migrations.AlterField(
            model_name='targetdataset',
            name='partial_load',
            field=models.ManyToManyField(blank=True, db_table='target_dataset_partial_load', help_text='Optional Partial Loads for which this dataset is an explicit execution root. Required upstream dependencies and mandatory system-managed companions are resolved automatically. System-managed history datasets must not be assigned as explicit roots.', related_name='datasets', to='metadata.partialload'),
        ),
    ]
