"""
elevata - Metadata-driven Data Platform Framework
Copyright © 2025 Ilona Tag

This file is part of elevata.

elevata is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of
the License, or (at your option) any later version.

elevata is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with elevata. If not, see <https://www.gnu.org/licenses/>.

Contact: <https://github.com/elevata-labs/elevata>.
"""

"""
Django settings for elevata_site project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv, find_dotenv 
import dj_database_url
from utils.env import env_bool, env_list, env_str, env_int
from utils.db import build_metadata_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(find_dotenv(filename=".env", raise_error_if_not_found=False))

STATIC_URL = "static/"

STATICFILES_DIRS = [
  BASE_DIR / "static", 
  BASE_DIR.parent / "docs",
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-only-unsafe")

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", [])

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)
SECRET_KEY = env_str("SECRET_KEY", "dev-only-insecure")

# Application definition

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'metadata',
]

MIDDLEWARE = [
  # Ensure CommonMiddleware is enabled
  "django.middleware.security.SecurityMiddleware",
  "django.contrib.sessions.middleware.SessionMiddleware",
  "django.middleware.common.CommonMiddleware",
  "django.middleware.csrf.CsrfViewMiddleware",
  "django.contrib.auth.middleware.AuthenticationMiddleware",
  "django.contrib.messages.middleware.MessageMiddleware",
  "django.middleware.clickjacking.XFrameOptionsMiddleware",
  "elevata_site.middleware.LoginRequiredAllMiddleware",
]

APPEND_SLASH = True

ROOT_URLCONF = 'elevata_site.urls'

TEMPLATES = [
  {
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [BASE_DIR / "templates"],
    "APP_DIRS": True,
    "OPTIONS": {
      "context_processors": [
        "django.template.context_processors.debug",
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
        "elevata_site.context_processors.app_menu",
      ],
    },
  },
]

WSGI_APPLICATION = 'elevata_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = build_metadata_database_url(BASE_DIR)

DATABASES = {
  "default": dj_database_url.parse(
    DATABASE_URL,
    conn_max_age=env_int("DB_CONN_MAX_AGE", 60),
    ssl_require=env_bool("DB_SSL_REQUIRE", False),
  )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ELEVATA_CRUD = {
  "metadata": {
    "order": [
      "Team", 
      "Person", 
      "PartialLoad", 
      "SourceSystem", 
      "SourceDataset", 
      "SourceDatasetOwnership", 
      "SourceColumn", 
      "TargetDataset", 
      "TargetDatasetOwnership", 
      "TargetColumn", 
      "TargetDatasetReference"
      ],
    "descriptions": {
      "Team": "Organize data teams, functional groups.",
      "Person": "Track users and their relation to the teams within your data organization.",
      "PartialLoad": "Define additional loads to process subsets of your datasets in individual frequencies.",
      "SourceSystem": "Register and describe upstream systems providing raw data to the platform.",
      "SourceDataset": "Define datasets extracted from source systems — the entry point for ingestion.",
      "SourceDatasetOwnership": "Assign accountability for source datasets and document responsibilities.",
      "SourceColumn": "Capture technical metadata and profiling details for each source column.",
      "TargetDataset": "Design target datasets for your platform and map them to the source datasets.",
      "TargetDatasetOwnership": "Assign ownership and stewardship for target datasets across teams.",
      "TargetColumn": "Define business-ready columns and maintain data quality at the attribute level.",
      "TargetDatasetReference": "Specify relations between the target datasets to generate appropriate foreign surrogate keys.",
    },
    "icons": {
      "Team": "users",
      "Person": "user",
      "PartialLoad": "timer",
      "SourceSystem": "database",
      "SourceDataset": "file",
      "SourceDatasetOwnership": "shield-check",
      "SourceColumn": "grid-2x2",
      "TargetDataset": "file-check-2",
      "TargetDatasetOwnership": "shield-check",
      "TargetColumn": "grid-2x2-check",
      "TargetDatasetReference": "arrow-left-right",
    },
    "exclude": [""],
    "paths": {      
    },
  }
}

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
PASSWORD_CHANGE_REDIRECT_URL = "/"
