"""
elevata - Metadata-driven Data Platform Framework
Copyright © 2025-2026 Ilona Tag

This file is part of elevata.

elevata is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of
the License, or (at your option) any later version.

elevata is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with elevata. If not, see <https://www.gnu.org/licenses/>.

Contact: <https://github.com/elevata-labs/elevata>.
"""

# Integration-style template to check alias & naming conventions in preview SQL.

import pytest

from metadata.rendering.logical_plan import SourceTable, LogicalSelect, SelectItem
from metadata.generation import naming


class DummyTargetSchema:
  """Minimal schema-like object for naming tests."""
  physical_prefix = "rc"
  short_name = "raw"


class DummySystem:
  short_name = "sap1"
  target_short_name = "sap"


class DummySourceDataset:
  source_system = DummySystem()
  source_dataset_name = "customer"


@pytest.fixture
def physical_name_for_preview():
  """
  Use your naming logic to derive a physical target table name
  from a source dataset and target schema.
  """
  schema = DummyTargetSchema()
  source = DummySourceDataset()
  return naming.build_physical_dataset_name(schema, source)


@pytest.fixture
def logical_select_for_physical_name(physical_name_for_preview):
  """
  Create a LogicalSelect that conceptually matches the physical name
  generated by naming.build_physical_dataset_name.
  """
  # Suppose your preview selects from that physical table
  from_table = SourceTable(
    schema=None,  # Optional: you may choose to add a schema
    name=physical_name_for_preview,
    alias="t",
  )

  dummy_expr = object()  
  select_items = [
    SelectItem(expr=dummy_expr, alias="row_count"),
  ]

  return LogicalSelect(
    from_=from_table,
    select_list=select_items,
  )


@pytest.mark.skip(reason="Connect this to your real preview renderer once available.")
def test_preview_uses_expected_physical_name(logical_select_for_physical_name, physical_name_for_preview):
  """
  Once wired, this test should ensure that the preview SQL uses the
  physical dataset name derived by the naming logic.
  """
  # Example:
  # from metadata.preview import build_preview_sql
  # sql = build_preview_sql(logical_select_for_physical_name)

  from metadata.rendering.preview import build_preview_sql  # type: ignore  # noqa: F401
  sql = build_preview_sql(logical_select_for_physical_name)  # type: ignore  # noqa: F821

  lowered = sql.lower()
  expected = physical_name_for_preview.lower()

  assert expected in lowered
  assert "from" in lowered
